config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      post :comment
      put :publish
    end
  end
  root to: "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Shared::Publishable

  belongs_to :user
  belongs_to :post
end

app/models/concerns/shared/publishable.rb
module Shared::Publishable
  extend ActiveSupport::Concern

  included do
    def self.published
      where("published_at < ?", DateTime.now)
    end

    def self.published_or_owned_by(user = nil)
      return published if user.blank?
      where("published_at < ? OR user_id = ?", DateTime.now, user.id)
    end

    def published?
      published_at.present? && published_at < DateTime.now
    end

    def unpublished?
      !published?
    end

    def publish
      update_attribute(:published_at, DateTime.now)
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Shared::Publishable

  extend FriendlyId
  friendly_id :title

  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments

  validates_presence_of :title, :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_post, only: [:show, :edit, :update, :publish, :comment, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.published_or_owned_by(current_user)
    @posts = PostDecorator.decorate_collection(@posts)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    respond_to do |format|
      if @post.publish
        format.html { redirect_to @post, notice: 'Post was successfully published.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def comment
    @comment= Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.published_or_owned_by(current_user).friendly.find(params[:id]).decorate
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :slug, :content, :published_at)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/timeago_helper.rb
module TimeagoHelper
  def timeago(timestamp, options = {})
    options[:class] ||= "timeago"
    options[:class] += " timeago" unless options[:class].match(/timeago/)

    content_tag(:abbr, l(timestamp),
                options.merge(title: timestamp.getutc.iso8601)) if timestamp
  end
end

app/views/comments/_comment.html.erb
<% if comment.persisted? %>
<div class="comment">
  <p>On <%= l(comment.created_at) %>, by <%= comment.user && comment.user.email %></p>
  <%= comment.content %>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, url: comment_post_path(@post)) do |c| %>
  <%= c.label :content %>
  <%= c.text_area :content, class: "form-control", placeholder: "Type your comment here..." %>
  <%= c.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RailsGirls</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "RailsGirls Project", "/", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <% if user_signed_in? %>
            <li class="active"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="active"><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control", placeholder: "Type your post content here..." %>
  </div>
  <div class="actions">
    <%= link_to "Back", posts_path, class: 'btn btn-default' %>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post<%= " unpublished" if post.unpublished? %>">
<h1>
  <% if post.unpublished? %>
  <%= link_to "Publish", publish_post_path(post), method: :put, class: "btn btn-success" %>
  <% end %>
  <%= link_to post.title, post %>
</h1>
<p>On <%= timeago(post.created_at) %>, by <%= post.user && post.user.email %></p>
<%= post.content %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="posts">
  <h1>My Blog</h1>

  <%= render @posts %>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<article class="post<%= " unpublished" if @post.unpublished? %>">
  <h1>
    <% if @post.unpublished? %>
    <%= link_to "Publish", publish_post_path(@post), method: :put, class: "btn btn-success" %>
    <% end %>
    <%= @post.title %>
  </h1>
  <p>On <%= timeago(@post.created_at) %>, by <%= @post.user && @post.user.email %></p>

  <%= @post.content %>

  <section class="comments">
    <h2>Comments</h2>

    <%= render CommentDecorator.decorate_collection(@post.comments) %>
    <% if user_signed_in? %>
      <% if @post.unpublished? %>
      <div class="bs-callout bs-callout-info">
        <h4>Placing comments</h4>
        <p>You need to <%= link_to "publish your post", publish_post_path(@post), method: :put %> to allow comments.</p>
      </div>
      <% else %>
      <%= render 'comments/form' %>
      <% end %>
    <% else %>
      <div class="bs-callout bs-callout-info">
        <h4>Placing comments</h4>
        <p>You need to <%= link_to "sign in", new_user_session_path %> to place comments.</p>
      </div>
    <% end %>
  </section>
</article>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>